# Generated by Django 6.0 on 2025-12-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Оригинальный формат'),
        ),
    ]
