# Generated by Django 6.0 on 2026-01-08 16:45

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_original_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Будет создано автоматически из видео', null=True, upload_to=videos.models.thumbnail_upload_path, verbose_name='Превью'),
        ),
    ]
